### ISSUE TITLE
asitop command wont work after installation Ventura

### ISSUE THREAD

**Issue by natsukirei** [tlkh/asitop#49]
hey guys

Ive been trying to get asitop to work but i get the following output, seems like some sort of PATH issue

`natsukirei@Lukes-Mac-Studio ~ % pip3 install git+https://github.com/SuperKenVery/asitop.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/SuperKenVery/asitop.git
  Cloning https://github.com/SuperKenVery/asitop.git to /private/var/folders/fy/3cg2scgs4q7dvt18hvnrf_bw0000gn/T/pip-req-build-24bp443w
  Running command git clone --filter=blob:none --quiet https://github.com/SuperKenVery/asitop.git /private/var/folders/fy/3cg2scgs4q7dvt18hvnrf_bw0000gn/T/pip-req-build-24bp443w
  Resolved https://github.com/SuperKenVery/asitop.git to commit 9a67ed7eebd95370d6b97fd9821b4ef1628ff613
  Preparing metadata (setup.py) ... done
Requirement already satisfied: dashing in ./Library/Python/3.9/lib/python/site-packages (from asitop==0.0.21) (0.1.0)
Requirement already satisfied: psutil in ./Library/Python/3.9/lib/python/site-packages (from asitop==0.0.21) (5.9.4)
Requirement already satisfied: blessed in ./Library/Python/3.9/lib/python/site-packages (from dashing->asitop==0.0.21) (1.19.1)
Requirement already satisfied: six>=1.9.0 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from blessed->dashing->asitop==0.0.21) (1.15.0)
Requirement already satisfied: wcwidth>=0.1.4 in ./Library/Python/3.9/lib/python/site-packages (from blessed->dashing->asitop==0.0.21) (0.2.5)
Building wheels for collected packages: asitop
  Building wheel for asitop (setup.py) ... done
  Created wheel for asitop: filename=asitop-0.0.21-py3-none-any.whl size=9180 sha256=4c74e00e58c4a58a940ed45e517e356aca90668d925ddb6fcfb869161f53accd
  Stored in directory: /private/var/folders/fy/3cg2scgs4q7dvt18hvnrf_bw0000gn/T/pip-ephem-wheel-cache-8cwteb4o/wheels/06/e0/2c/f097fa055ab84bb08a213e9e75f9ee496a4979ef98f897328a
Successfully built asitop
Installing collected packages: asitop
  WARNING: The script asitop is installed in '/Users/natsukirei/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed asitop-0.0.21
natsukirei@Lukes-Mac-Studio ~ % asitop
zsh: command not found: asitop`

**Comment by BitesPotatoBacks** [comment]
@natsukirei Adding `/Users/natsukirei/Library/Python/3.9/bin` to your PATH var (likely contained in either `.zshrc` or `.bashrc`) should resolve this problem.

**Comment by natsukirei** [comment]
> @natsukirei Adding `/Users/natsukirei/Library/Python/3.9/bin` to your PATH var (likely contained in either `.zshrc` or `.bashrc`) should resolve this problem.

thanks, but i have absolutely no idea how to do this, is their a guide somewhere

**Comment by BitesPotatoBacks** [comment]
@natsukirei

You could open `~/.zshrc` in a text editor and append `export PATH=/Users/natsukirei/Library/Python/3.9/bin:$PATH` to the end of the file. 

If you want to do it from the command line, it should be easy as...
```bash
printf "\nexport PATH=/Users/natsukirei/Library/Python/3.9/bin:\$PATH" >> ~/.zshrc
```

**Note for either methods:** use `~/.bashrc` instead of `~/.zshrc` if you _don't_ use zsh nor the native MacOS terminal.

Hopefully that helps a bit 🙂

**Comment by nivaldin** [comment]
Same problem here, tried the @BitesPotatoBacks solution but still won't work.

**Comment by BitesPotatoBacks** [comment]
@nivaldin That's strange, that method should work (it's worked for me when applying to other tools).

I guess until this is fixed by the maintainer, we could all just move the asitop binary directly into `usr/bin` or `usr/local/bin` 😑

**Comment by Vlor999** [comment]
Hi everyone, since this project seems to be unmaintained and has accumulating bugs with recent macOS updates, I've created an actively maintained fork called mxtop. It includes pending community fixes and is fully working on the latest Apple Silicon chips.
You can install it right now using: pip install mxtop The new repository is here: https://github.com/Vlor999/mxtop
Feel free to open issues or PRs there!
